# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNewsFeedExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNewsFeedExample
  pod 'OAuthSwift'
  pod 'Gloss'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'RealmSwift'

  target 'SwiftNewsFeedExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftNewsFeedExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
